version: '3'
services:
  myapp:
    build: .
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - myapp

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword
    depends_on:
      - prometheus